### PR TITLE
Update webjars and generated code

### PR DESCRIPTION
**Pull request by ZheSun88**
Add two new APIs from the generated class

This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-upload-flow/44)

### CODE REVIEW

**Comment by gilberto-torrezan** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/main/java/com/vaadin/flow/component/upload/Upload.java, line 170 at r1](https://reviewable.io/reviews/vaadin/vaadin-upload-flow/44#-LB4bzmV-cGlQaBcVPdy:-LB4bzmV-cGlQaBcVPdz:bcjvjer) ([raw file](https://github.com/vaadin/vaadin-upload-flow/blob/f9706109b1ae9bb0f739bf841500ec819743035b/src/main/java/com/vaadin/flow/component/upload/Upload.java#L170)):*
> ```Java
>     public String getCapture() {
>         return super.getCaptureString();
>     }
> ```

I suggest removing those methods from the public API for now, since we don't have a demo or documentation about how do they work. We can always add them later if needed.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-upload-flow/44)*

**Comment by ZheSun88** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/vaadin/flow/component/upload/Upload.java, line 170 at r1](https://reviewable.io/reviews/vaadin/vaadin-upload-flow/44#-LB4bzmV-cGlQaBcVPdy:-LB4n4xL3e7mqYFfu8w2:b-89rjll) ([raw file](https://github.com/vaadin/vaadin-upload-flow/blob/f9706109b1ae9bb0f739bf841500ec819743035b/src/main/java/com/vaadin/flow/component/upload/Upload.java#L170)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

I suggest removing those methods from the public API for now, since we don't have a demo or documentation about how do they work. We can always add them later if needed.
</blockquote></details>

DONE.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-upload-flow/44)*

**Comment by gilberto-torrezan** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/vaadin/flow/component/upload/Upload.java, line 170 at r1](https://reviewable.io/reviews/vaadin/vaadin-upload-flow/44#-LB4bzmV-cGlQaBcVPdy:-LB4nOYcBmKoQmGY0U_D:b-8ya0ep) ([raw file](https://github.com/vaadin/vaadin-upload-flow/blob/f9706109b1ae9bb0f739bf841500ec819743035b/src/main/java/com/vaadin/flow/component/upload/Upload.java#L170)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

DONE.
</blockquote></details>

No need to scream =P

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-upload-flow/44)*

**Comment by gilberto-torrezan** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-upload-flow/44#-:-LB4nUu-B3uYwN72ycYF:bnfp4nl)*

**Comment by ZheSun88** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/main/java/com/vaadin/flow/component/upload/Upload.java, line 170 at r1](https://reviewable.io/reviews/vaadin/vaadin-upload-flow/44#-LB4bzmV-cGlQaBcVPdy:-LB4nznZ3KI1ZeUJ2AdG:b-re0yzr) ([raw file](https://github.com/vaadin/vaadin-upload-flow/blob/f9706109b1ae9bb0f739bf841500ec819743035b/src/main/java/com/vaadin/flow/component/upload/Upload.java#L170)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

No need to scream =P
</blockquote></details>

UNFORTUNATELY.. I HAVE CAPSLOCK ON...

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-upload-flow/44)*

**Pull request merged**
